name: Fetch and Push CAPACOA data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  fetch-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Fetch data
        run: bundle exec ruby src/fetch_data.rb
        
      - name: Add schema and member type
        run: bundle exec ruby src/add_type.rb

      - name: Start OntoRefine with Docker Compose
        run: docker compose up -d
    
      - name: Wait for OntoRefine to be ready
        run: |
            echo "Waiting for server to start..."
            while ! curl --output /dev/null --silent --head --fail http://localhost:7333; do
            sleep 5
            done
            echo "Server started!"

      - name: Run OntoRefine CLI transformation
        run: |
          docker exec onto_refine /opt/ontorefine/dist/bin/ontorefine-cli transform /opt/data/members.json \
            -u http://localhost:7333 \
            --no-clean \
            --configurations /opt/data/ontorefine/ontorefine-config.json \
            -f json > ontorefine-output.ttl

      - name: Run SPARQL to infer presenter type
        run: bundle exec ruby src/run_sparql.rb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ttl-file
            path: output/

  commit-and-push:
    runs-on: ubuntu-latest
    needs: fetch-and-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        id: download-step
        uses: actions/download-artifact@v4
        with:
            name: ttl-file
            path: output/
      - name: Push files to GitHub if there are changes
        run: |
            git pull
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add output/
            if ! git diff --cached --quiet; then
              git commit -m "Push Entities from CAPACOA"
              git push
            else
              echo "No changes to commit."
            fi

  artsdata-push:
    runs-on: ubuntu-latest
    needs: commit-and-push
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
            artifact: capacoa-members
            publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
            downloadUrl: https://raw.githubusercontent.com/${{github.repository}}/${{github.ref}}/output/data.ttl
