name: Push Showcase Events Entities

# For more information about this workflow, see this CAPACOA GitHub repository: https://github.com/capacoa/showcase-events

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"  # Run at 1:00 AM ET every Monday

jobs:
  artsdata-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v4
        with:
          mode: push
          artifact: showcase-events
          publisher: "https://github.com/fjjulien#this"
          downloadUrl: "https://raw.githubusercontent.com/capacoa/showcase-events/refs/heads/main/output/showcase-events.json"
