PREFIX schema: <http://schema.org/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

CONSTRUCT {
  ?wdid wdt:P2002 ?twitterUsername ;
        wdt:P2013 ?facebookId ;
        wdt:P2003 ?instagramUsername .
}
WHERE {
  VALUES ?wdid { <http://placeholder> }
  OPTIONAL { ?wdid wdt:P2002 ?twitterUsername . }
  OPTIONAL { ?wdid wdt:P2013 ?facebookId . }
  OPTIONAL { ?wdid wdt:P2003 ?instagramUsername . }
}
